name: Go
on: [push]
jobs:
  pre-build:
    name: Create env
    steps:
      - name: Set up Go 1.13.5
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.5
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

  build:
    name: Build
    runs-on: Ubuntu-latest
    steps:
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Real build
        run: /bin/bash build.sh
